feat:添加 GitHub 访问不可达测试 (#81)
* Update install.sh

* 通过 curl 等工具替代git 下载

* 忽略非异常输出

* 添加 GitHub 不可达情况测试

* 适配 action 环境

* 多部分扩展名处理

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -50,6 +50,33 @@ jobs:
           echo "LiteLoader found in output and /opt/LiteLoader/plugins directory exists. Test succeeded."
         fi
 
+    - name: Set up iptables rules
+      run: |
+        # 阻止访问 GitHub
+        sudo iptables -A OUTPUT -d github.com -j REJECT
+
+    - name: Remove LiteLoader directory
+      run: |
+        if [ -d "/opt/LiteLoader" ]; then
+          # 删除目录及其内容
+          rm -rf "/opt/LiteLoader"
+          echo "LiteLoader directory removed successfully."
+        else
+          echo "LiteLoader directory does not exist."
+        fi
+
+    - name: ReRun install.sh
+      run: |
+        ./install.sh
+
+    - name: Check output again
+      run: |
+        if ! /opt/QQ/qq --logging-enable | grep -q "[LiteLoader]" || [ ! -d "/opt/LiteLoader/plugins" ]; then
+          echo "LiteLoader not found in output or /opt/LiteLoader/plugins directory does not exist. Test failed."
+          exit 1
+        else
+          echo "LiteLoader found in output and /opt/LiteLoader/plugins directory exists. Test succeeded."
+        fi
 
   release:
     runs-on: ubuntu-latest
diff --git a/.github/workflows/macOS.yml b/.github/workflows/macOS.yml
--- a/.github/workflows/macOS.yml
+++ b/.github/workflows/macOS.yml
@@ -58,7 +58,41 @@ jobs:
           exit 1
         fi
 
+    - name: Set up iptables rules
+      run: |
+        # 阻止访问 GitHub
+        echo "127.0.0.1 github.com" | sudo tee -a /etc/hosts
+        echo "127.0.0.1 api.github.com" | sudo tee -a /etc/hosts
 
+    - name: Remove LiteLoader directory
+      run: |
+        if [ -d "$HOME/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader" ]; then
+          # 删除目录及其内容
+          rm -rf "$HOME/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader"
+          echo "LiteLoader directory removed successfully."
+        else
+          echo "LiteLoader directory does not exist."
+        fi
+
+    - name: ReRun install.sh
+      run: |
+        ./install.sh
+
+    - name: Check LiteLoader
+      run: |
+        /Applications/QQ.app/Contents/MacOS/QQ &  # 启动 QQ，放入后台
+        sleep 3  # 等待 3 秒
+
+        # 关闭 QQ 应用程序，这里使用 pkill 假设 QQ 进程的名字为 QQ
+        pkill QQ
+
+        # 检查 LiteLoader 插件是否存在
+        if [ -d "$HOME/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins" ]; then
+          echo "LiteLoader plugins folder exists. Test succeeded."
+        else
+          echo "LiteLoader plugins folder does not exist. Test failed."
+          exit 1
+        fi
 
   release:
     runs-on: ubuntu-latest
