mac 添加自动安装插件商店

diff --git a/.github/workflows/macOS.yml b/.github/workflows/macOS.yml
--- a/.github/workflows/macOS.yml
+++ b/.github/workflows/macOS.yml
@@ -43,3 +43,13 @@ jobs:
           echo "LiteLoader plugins folder does not exist. Test failed."
           exit 1
         fi
+
+    - name: Check LiteLoader Store
+      run: |
+        # 检查 LiteLoader 插件是否存在
+        if [ -d "$USER_HOME/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/pluginStore" ]; then
+          echo "LiteLoader pluginStore folder exists. Test succeeded."
+        else
+          echo "LiteLoader pluginStore folder does not exist. Test failed."
+          exit 1
+        fi
